### ISSUE TITLE
Plugin tests crash with ember-template-lint@2.9.0

### ISSUE THREAD

**Issue by andreyfel** [ember-template-lint/ember-template-lint#1401]
Test looks like:
```
'use strict';

const generateRuleTests = require('ember-template-lint/lib/helpers/rule-test-harness');
const plugin = require('../../../lib');

generateRuleTests({
  plugins: [plugin],
...
```

The exception is the following:
```
TypeError: configPlugins is not iterable

      at processPlugins (../node_modules/ember-template-lint/lib/get-config.js:161:24)
      at ../node_modules/ember-template-lint/lib/get-config.js:197:32
      at forEachPluginConfiguration (../node_modules/ember-template-lint/lib/get-config.js:98:7)
      at processPlugins (../node_modules/ember-template-lint/lib/get-config.js:195:3)
      at getProjectConfig (../node_modules/ember-template-lint/lib/get-config.js:493:5)
      at Linter.loadConfig (../node_modules/ember-template-lint/lib/linter.js:47:19)
      at new Linter (../node_modules/ember-template-lint/lib/linter.js:39:10)
      at Object.<anonymous> (../node_modules/ember-template-lint/lib/helpers/rule-test-harness.js:141:16)
```

It works with ember-template-lint@2.8.0

**Comment by andreyfel** [comment]
I think it is related to this change:
https://github.com/ember-template-lint/ember-template-lint/commit/0d8ad50336821ef8513a60bcb8efce2f4a77b675#diff-167aef5ef69408a64527334a4ce07ab5
This: `for (let i = 0; i < configPlugins.length; i++) {` changed to `for (let plugin of configPlugins) {`

**Comment by bmish** [comment]
That's strange. From your code, I see that `plugins` is an array, so it should be iterable. If possible, could you add a print statement right in front of this for-of loop so we can see what `configPlugins` looks like?

```js
console.log(`configPlugins: ${JSON.stringify(configPlugins)}`);
```

I tested my own custom plugin rule with v2.9.0 and I don't encounter a crash. I have the same code with `generateRuleTests` as you.

**Comment by amk221** [comment]
Morning 👋 
also seeing this today

**Comment by amk221** [comment]
@bmish
```
configPlugins: ["@zestia/ember-template-lint-plugin"]
configPlugins: undefined
```
