### ISSUE TITLE
[Discussion] Any pointers to run template lint in parallel ?

### ISSUE THREAD

**Issue by siva-sundar** [ember-template-lint/ember-template-lint#1860]
Looking for ways to run template lint in parallel in our project. We have close to 3.5k templates.

Suggestions would be really appreciated.

**Comment by bmish** [comment]
How long does it take you to run it out of curiosity?

It takes me ~1 minute to run handlebars linting on my application with ~3,000 handlebars files containing ~100,000 lines of code (ember-template-lint v3 with most recommended rules, recent MacBook Pro, counted lines of code with [cloc](https://github.com/AlDanial/cloc)).

**Comment by rwjblue** [comment]
We definitely can leverage worker threads when available, we've generally avoided it because of what @bmish mentioned: I find it to be quite fast (compared to eslint).

**Comment by siva-sundar** [comment]
Handlebars ~190000 loc

ember-template-lint v3 with some recommended rules and a few custom rules, it takes ~ 321s.

**Comment by bmish** [comment]
I would love it if we added per-rule performance metrics like [eslint has](https://eslint.org/docs/developer-guide/working-with-rules#per-rule-performance) to help determine which rules are the most expensive to run.

**Comment by lifeart** [comment]
According to performance debug of https://github.com/lifeart/ember-template-lint-typed-templates, I found that one rule may be required (uncached) few times, it may be an point of "slowness".

**Comment by runspired** [comment]
template-lint (for me) is significantly slower than eslint. On a codebase with roughly 8k templates > 1M LOC (average CI times are close to 4min for the hbs portion of the linting.  eslint cold runs are a bit faster for similar stats. The biggest difference is in warm runs. eslint maintains a cache and can complete a warm run in a few seconds, template-lint does not seem to do this.

The caching may be of more interest to me here than the parallelism. Bringing down CI times would be nice but faster local feedback is much more important.

**Comment by lifeart** [comment]
Hey folks! Here is a PR: https://github.com/ember-template-lint/ember-template-lint/pull/3190

Having 2x performance improvement on ~1500 files project (from 16s to 7s)

If you have time to test it and report results - it will be a huge win!

cc @runspired , @NullVoxPopuli , @evoactivity , @boris-petrov

**Comment by SergeAstapov** [comment]
@lifeart this works great on local, did see only 12s to 10s reduction only `Linting 2412 Total Files with TemplateLint`

However we consistently face strange error in CI (running in Docker):
```
build	02-May-2025 12:34:17	my-app: [lint:hbs]
build	02-May-2025 12:34:17	my-app: [lint:hbs] node:internal/process/promises:394
build	02-May-2025 12:34:17	my-app: [lint:hbs]     triggerUncaughtException(err, true /* fromPromise */);
build	02-May-2025 12:34:17	my-app: [lint:hbs]     ^
build	02-May-2025 12:34:17	my-app: [lint:hbs] Error: Lock file is already being held
build	02-May-2025 12:34:17	my-app: [lint:hbs]     at /my-app/node_modules/.pnpm/proper-lockfile@4.1.2/node_modules/proper-lockfile/lib/lockfile.js:68:47
build	02-May-2025 12:34:17	my-app: [lint:hbs]     at newFs.<computed> [as stat] (/my-app/node_modules/.pnpm/proper-lockfile@4.1.2/node_modules/proper-lockfile/lib/adapter.js:20:13)
build	02-May-2025 12:34:17	my-app: [lint:hbs]     at /my-app/node_modules/.pnpm/proper-lockfile@4.1.2/node_modules/proper-lockfile/lib/lockfile.js:56:20
build	02-May-2025 12:34:17	my-app: [lint:hbs]     at newFs.<computed> [as mkdir] (/my-app/node_modules/.pnpm/proper-lockfile@4.1.2/node_modules/proper-lockfile/lib/adapter.js:17:24)
build	02-May-2025 12:34:17	my-app: [lint:hbs]     at acquireLock (/my-app/node_modules/.pnpm/proper-lockfile@4.1.2/node_modules/proper-lockfile/lib/lockfile.js:29:16)
build	02-May-2025 12:34:17	my-app: [lint:hbs]     at RetryOperation._fn (/my-app/node_modules/.pnpm/proper-lockfile@4.1.2/node_modules/proper-lockfile/lib/lockfile.js:233:13)
build	02-May-2025 12:34:17	my-app: [lint:hbs]     at RetryOperation.attempt (/my-app/node_modules/.pnpm/retry@0.12.0/node_modules/retry/lib/retry_operation.js:112:8)
build	02-May-2025 12:34:17	my-app: [lint:hbs]     at /my-app/node_modules/.pnpm/proper-lockfile@4.1.2/node_modules/proper-lockfile/lib/lockfile.js:232:19
build	02-May-2025 12:34:17	my-app: [lint:hbs]     at newFs.<computed> [as realpath] (/my-app/node_modules/.pnpm/proper-lockfile@4.1.2/node_modules/proper-lockfile/lib/adapter.js:20:13)
build	02-May-2025 12:34:17	my-app: [lint:hbs]     at resolveCanonicalPath (/my-app/node_modules/.pnpm/proper-lockfile@4.1.2/node_modules/proper-lockfile/lib/lockfile.js:22:16) {
build	02-May-2025 12:34:18	my-app: [lint:hbs]   code: "'ELOCKED'",
build	02-May-2025 12:34:18	my-app: [lint:hbs]   file: "'/my-app/apps/my-app/.lint-todo'"
build	02-May-2025 12:34:18	my-app: [lint:hbs] }
build	02-May-2025 12:34:18	my-app: [lint:hbs]
build	02-May-2025 12:34:18	my-app: [lint:hbs] Node.js v22.12.0
```

looks like [`readTodos` function in `@lint-todo/utils`](https://github.com/lint-todo/utils/blob/b9fc8d93c0cb69d9ef422faa46c4fb7e4e83b1bc/src/io.ts#L184) uses [`proper-lockfile`](https://www.npmjs.com/package/proper-lockfile) for safe read operation.

our CI agent has 32 CPUs available, so I guess we consistently hit locks.

if I'm not mistaken, It seems in #3190 you made it in a way to process 10 files in parallel within each worker.
not sure how to limit number of workers in our case, thinking if we can introduce a new argument like `--workers-count` so we could e.g. specify 8 instead of number of CPUs available

**Comment by lifeart** [comment]
@SergeAstapov could you try https://github.com/ember-template-lint/ember-template-lint/pull/3198?
