### ISSUE TITLE
Error when using --fix with no-model-argument-in-route-templates rule

### ISSUE THREAD

**Issue by meirish** [ember-template-lint/ember-template-lint#2027]
I have a monorepo with yarn workspaces and some of the packages error out when running `yarn lint:hbs:fix` - `yarn lint:hbs` works properly, showing the errant templates in the output, and removing `no-model-argument-in-route-templates` also allows lint to run without error.

This is the error:
```$ ember-template-lint . --fix
(node:41662) UnhandledPromiseRejectionWarning: TypeError: ast.params.map is not a function
    at ParseResult._rebuildParamsHash (.../node_modules/ember-template-recast/lib/parse-result.js:274:48)
    at ParseResult.print (.../node_modules/ember-template-recast/lib/parse-result.js:517:26)
    at .../node_modules/ember-template-recast/lib/parse-result.js:274:68
    at Array.map (<anonymous>)
    at ParseResult._rebuildParamsHash (.../node_modules/ember-template-recast/lib/parse-result.js:274:48)
    at ParseResult.print (.../node_modules/ember-template-recast/lib/parse-result.js:640:26)
    at .../node_modules/ember-template-recast/lib/parse-result.js:420:75
    at Array.map (<anonymous>)
    at ParseResult.print (.../node_modules/ember-template-recast/lib/parse-result.js:420:55)
    at .../node_modules/ember-template-recast/lib/parse-result.js:319:66
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41662) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:41662) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

Any pointers?

**Comment by meirish** [comment]
One odd thing - there are a handful of templates that are fixed properly.

**Comment by meirish** [comment]
I'm not sure if this is the same as https://github.com/ember-template-lint/ember-template-lint/issues/1648 or not... each run is invoked the same way (neither with an absolute path).

**Comment by meirish** [comment]
moved to https://github.com/ember-template-lint/ember-template-recast/issues/610
