### ISSUE TITLE
Flaky TODO tests

### ISSUE THREAD

**Issue by bmish** [ember-template-lint/ember-template-lint#2298]
I'm seeing flaky TODO tests in the `next` branch. They appear to be taking too long to run sometimes. This is affecting many PR builds. CC: @scalvert 

Example: https://github.com/ember-template-lint/ember-template-lint/runs/4622239615?check_suite_focus=true

```
FAIL test/acceptance/todo-cli-test.js (162.234 s)
  ● todo usage › with/without --update-todo and --include-todo params › cleaning todos not in CI › errors if a todo item is no longer valid when running with --no-clean-todo, and cleans using --fix

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      410 |       setupEnvVar('GITHUB_ACTIONS', null);
      411 |
    > 412 |       it('errors if a todo item is no longer valid when running with --no-clean-todo, and cleans using --fix', async function () {
          |       ^
      413 |         project.setConfig({
      414 |           rules: {
      415 |             'require-button-type': true,

      at test/acceptance/todo-cli-test.js:412:7
      at test/acceptance/todo-cli-test.js:408:5
      at test/acceptance/todo-cli-test.js:29:3
      at test/acceptance/todo-cli-test.js:14:1

  ● todo usage › with/without --update-todo and --include-todo params › cleaning todos not in CI › errors if a todo item is no longer valid when running with --no-clean-todo, and cleans using --fix

    EBUSY: resource busy or locked, rmdir 'C:\Users\RUNNER~1\AppData\Local\Temp\tmp-5976O4z8Yqh3SJbn\fake-project'

      144 |     }
      145 |
    > 146 |     return super.dispose();
          |                  ^
      147 |   }
      148 | }
      149 |

      at _rmdirRecursiveSync (node_modules/tmp/lib/tmp.js:314:10)
      at Object._cleanupCallback [as removeCallback] (node_modules/tmp/lib/tmp.js:446:7)
      at FakeProject.dispose (node_modules/fixturify-project/index.ts:312:17)
      at FakeProject.dispose (test/helpers/fake-project.js:146:18)
      at Object.<anonymous> (test/acceptance/todo-cli-test.js:26:13)
```

**Comment by scalvert** [comment]
Define flakey. This just appears to be a long running test. We do a lot of functional operations in those tests, so it's not surprising that they take a long time. We should just be able to increase the timeout.

**Comment by bmish** [comment]
It's failing 50% in the builds. Is it possible to split that test up? Or increasing the timeout for that specific test would be good too.

**Comment by scalvert** [comment]
I've added a timeout in #2303. That should do the trick.

I'd like to find out why this started occurring, and what specific change caused this. I'll leave the timeout in for now, if it fixes things, as a reminder to investigate.

**Comment by scalvert** [comment]
It looks as though the timeout helped here. I'll close this for now and we can reopen/dig deeper if needed.
