### ISSUE TITLE
Last version of ember-temlate-lint doesn't work anymore. Fail with ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by VincentMolinie** [ember-template-lint/ember-template-lint#2331]
# Description
I tried to upgrade this library from `3.6.0` to `4.0.0` but I can't lint anymore.
I'm using Node `14.17.6`

# Stacktrace 
```
(node:13517) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/ember-template-lint/lib/index.js
require() of ES modules is not supported.
require() of /node_modules/ember-template-lint/lib/index.js from /.lint-bin/attribute-quotes.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/ember-template-lint/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/.lint-bin/attribute-quotes.js:1:80)
    at Module._compile (/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13517) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13517) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by VincentMolinie** [comment]
My bad I did an import of ember-template-lint using `require`. The issue might come from here I think

**Comment by bmish** [comment]
Yes you'll need to use ESM now as mentioned here:

https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/migration/v4.md

> Integrations must now be written in ESM
