### ISSUE TITLE
ESM error in v4 consuming plugins in a Windows env

### ISSUE THREAD

**Issue by charlesfries** [ember-template-lint/ember-template-lint#2336]
I'm seeing the following error after updating `ember-template-lint` and `ember-template-lint-plugin-prettier` to 4.0.0.

```
(node:1584) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\cfries\Documents\Repositories\etlpp\node_modules\ember-template-lint-plugin-prettier\ember-template-lint-plugin-prettier.js
require() of ES modules is not supported.
require() of C:\Users\cfries\Documents\Repositories\etlpp\node_modules\ember-template-lint-plugin-prettier\ember-template-lint-plugin-prettier.js from C:\Users\cfries\Documents\Repositories\etlpp\node_modules\ember-template-lint\lib\get-config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename ember-template-lint-plugin-prettier.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\cfries\Documents\Repositories\etlpp\node_modules\ember-template-lint-plugin-prettier\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at requirePlugin (file:///C:/Users/cfries/Documents/Repositories/etlpp/node_modules/ember-template-lint/lib/get-config.js:38:12)
    at async processPlugins (file:///C:/Users/cfries/Documents/Repositories/etlpp/node_modules/ember-template-lint/lib/get-config.js:150:16)
    at async getProjectConfig (file:///C:/Users/cfries/Documents/Repositories/etlpp/node_modules/ember-template-lint/lib/get-config.js:396:22)
    at async Linter.loadConfig (file:///C:/Users/cfries/Documents/Repositories/etlpp/node_modules/ember-template-lint/lib/linter.js:48:19)
    at async Linter.verify (file:///C:/Users/cfries/Documents/Repositories/etlpp/node_modules/ember-template-lint/lib/linter.js:304:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Reproduction: https://github.com/charlesfries/etlpp

```
"ember-cli": "~4.0.1",
"ember-source": "~4.0.1",
"ember-template-lint": "^4.0.0",
"ember-template-lint-plugin-prettier": "^4.0.0",
```

```js
// .template-lintrc.js

'use strict';

module.exports = {
  plugins: ['ember-template-lint-plugin-prettier'],
  extends: ['recommended', 'ember-template-lint-plugin-prettier:recommended'],
};
```

**Comment by dcyriller** [comment]
This issue was initially opened in ember-template-lint-plugin-prettier. I transfer it to ember-template-lint, where we will fix it. Thanks for the report @charlesfries.

**Comment by lifeart** [comment]
I have seen it in uELS (once adding ember-template-lint v4 support), solution quite simple: we have to convert fs path to file path, will create PR
