### ISSUE TITLE
ESM config w/ `.mjs` not loadable?

### ISSUE THREAD

**Issue by maxfierke** [ember-template-lint/ember-template-lint#2453]
According to the v4 migration guide, because the app I'm working on directly imports rules, I need to convert it to ESM. However, when I do so, it doesn't seem like it can find the config?

Does this only work if `"type": "module"` is specified in `package.json`? I don't seem to be able to turn that on without infecting _everything_ and running into other add-ons (or `ember-cli`) that cannot find a corresponding `.cjs` file when _their_ configuration is still CommonJS.

```
$ yarn lint
yarn run v1.22.18
$ npm-run-all --aggregate-output --continue-on-error --parallel "lint:!(fix)"
(node:74494) UnhandledPromiseRejectionWarning: Error: The configuration file specified (.template-lintrc.js) could not be found. Aborting.
    at resolveProjectConfig (file:///Users/mfierke/src/MY_APP/node_modules/ember-template-lint/lib/get-config.js:68:13)
    at getProjectConfig (file:///Users/mfierke/src/MY_APP/node_modules/ember-template-lint/lib/get-config.js:407:41)
    at Linter.loadConfig (file:///Users/mfierke/src/MY_APP/node_modules/ember-template-lint/lib/linter.js:45:25)
    at Linter.verify (file:///Users/mfierke/src/MY_APP/node_modules/ember-template-lint/lib/linter.js:301:18)
    at run (file:///Users/mfierke/src/MY_APP/node_modules/ember-template-lint/bin/ember-template-lint.js:215:34)
(node:74494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:74494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What are my options here? I seem to need 4.x to fix parsing issues when trying to address the `argument-less-helper-paren-less-invocation` deprecation in Ember 3.27+ (ref https://github.com/ember-template-lint/ember-template-lint/issues/2163), otherwise I would just avoid upgrading until a point where I could ESM-ify everything.

**Comment by lifeart** [comment]
@maxfierke https://github.com/ember-template-lint/ember-template-lint/pull/2339 may fix it, could you create minimal test case for it?

**Comment by maxfierke** [comment]
Closing this out. I ended up abandoning whatever effort I was doing here and someone was able to get it working fine on v5 last week, so 🤷
