### ISSUE TITLE
Error: Must use import to load ES Module

### ISSUE THREAD

**Issue by iamdtang** [ember-template-lint/ember-template-lint#2479]
In a brand new Ember app (4.3.0), if I add the following to `.template-lintrc.js`:

```js
const { Rule } = require('ember-template-lint');
```

and then I run `npm run lint:hbs`, I get this error:

```
custom-template-lint-rule (main):npm run lint:hbs

> custom-template-lint-rule@0.0.0 lint:hbs
> ember-template-lint .

(node:10496) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/davidtang/Desktop/custom-template-lint-rule/node_modules/ember-template-lint/lib/index.js
require() of ES modules is not supported.
require() of /Users/davidtang/Desktop/custom-template-lint-rule/node_modules/ember-template-lint/lib/index.js from /Users/davidtang/Desktop/custom-template-lint-rule/.template-lintrc.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/davidtang/Desktop/custom-template-lint-rule/node_modules/ember-template-lint/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/Users/davidtang/Desktop/custom-template-lint-rule/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/davidtang/Desktop/custom-template-lint-rule/.template-lintrc.js:3:18)
    at Module._compile (/Users/davidtang/Desktop/custom-template-lint-rule/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chriskrycho** [comment]
This is as expected: ember-template-lint is now using ES modules, and the error message is telling you the necessary change:

- you can switch to using ESM directly yourself in the `.template-lintrc.js` (by setting `module: true` or by using `.mjs` as the extension for it)
- you can use `await import('ember-template-lint')` instead of `require('ember-template-lint')` if you want to keep treating that file as a CommonJS module

For more, see [Node's docs on modules](https://nodejs.org/api/packages.html).

**Comment by bmish** [comment]
Here's the migration guide: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/migration/v4.md
