### ISSUE TITLE
Linting breaks running ember instance due to missing lockfile

### ISSUE THREAD

**Issue by michaelchadwick** [ember-template-lint/ember-template-lint#3093]
Whenever I run `ember-template-lint` (specifically on `.hbs` files), my running `ember serve` instance dies due to not being able to find the `.lint-todo.lock` file. I think that it never gets created in the first place, so it's never going to find it.

This only happens on one particular EmberJS (`ember-cli: 5.9.0, node: 20.12.2, os: darwin arm64`) project, and not a new I just create. I checked file/dir permissions and they are the same in both the working and non-working projects.

E.g.
```
node:internal/fs/watchers:255
    throw error;
    ^

Error: ENOENT: no such file or directory, watch '~/code/project/lint-todo.lock'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2464:36)
    at NodeWatcher.watchdir (~/code/project/node_modules/.pnpm/sane@4.1.0/node_modules/sane/src/node_watcher.js:159:22)
    at NodeWatcher.<anonymous> (~/code/project/node_modules/.pnpm/sane@4.1.0/node_modules/sane/src/node_watcher.js:295:18)
    at FSReqCallback.oncomplete (node:fs:205:5) {
  errno: -2,
  syscall: 'watch',
  code: 'ENOENT',
  path: '~/code/project/packages/common/.lint-todo.lock',
  filename: '~/code/project/packages/common/.lint-todo.lock'
}
```

**Comment by lifeart** [comment]
Moving issue to umbrella ticket https://github.com/ember-template-lint/ember-template-lint/issues/new and closing it here (for now)
