### ISSUE TITLE
CLI does not respond

### ISSUE THREAD

**Issue by josemarluedke** [ember-template-lint/ember-template-lint#536]
I'm been trying to execute the CLI (`yarn run lint:hbs`) and it always hangs.

The script corresponds to executing `ember-template-lint .`. It just doesn't return anything, no errors or any feedback.

If I have the ember server at the same time and I kill the server, then the template lint resolves with an error like this:

```
➜ yarn run lint:hbs
yarn run v1.10.1
$ ember-template-lint .
/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:51
      throw err;
      ^

Error: ENOENT: no such file or directory, scandir '/Users/josemarluedke/code/my-project/my-project-ui/tmp/funnel-input_base_path-UwzVJtkb.tmp/tmp/broccoli_merge_trees-output_path-N9ZUxHR7.tmp/tests/addon-test-support'
    at Object.readdirSync (fs.js:764:3)
    at exports.readdir (/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at Readable.DirectoryReader.stream._read (/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (_stream_readable.js:452:10)
    at maybeReadMore_ (_stream_readable.js:569:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
Emitted 'error' event at:
    at DirectoryReader.emit (/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:365:14)
    at call.safe (/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:81:14)
    at onceWrapper (/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:45:17)
    at onceWrapper (/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:45:17)
    at exports.readdir (/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:22:5)
    at Object.safeCall [as safe] (/Users/josemarluedke/code/my-project/my-project-ui/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    [... lines matching original stack trace ...]
    at maybeReadMore_ (_stream_readable.js:569:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
➜ ember -v

ember-cli: 3.4.3
node: 10.11.0
os: darwin x64
```

I have v1.0.0-beta.6 of ember-template-lint

If desired, I can create a reproduction of this problem.

**Comment by rwjblue** [comment]
Ugh. Seems like it is trying to lint your tmp dirs. 😩

**Comment by josemarluedke** [comment]
Yeah, seems to be the case. Just removed all my tmp folder and `yarn lint:hbs` did resolve right away.

**Comment by amk221** [comment]
Ahh, I'm also getting this. I think it was also trying to lint node_modules

**Comment by Duder-onomy** [comment]
The CLI is hanging for me right now. 

I run `node --inspect-brk ./node_modules/.bin/ember-template-lint app/**/*.hbs`

I get to this globby call:
https://github.com/ember-template-lint/ember-template-lint/blob/master/bin/ember-template-lint.js#L64
![image](https://user-images.githubusercontent.com/1612785/48640051-5d9b0800-e98a-11e8-8be9-9235613fb5ab.png)

Things completely stop and never return.  Just me and my terminal... hanging out. 

-- 
If I step into Globby, we eventually get to this line:
https://github.com/sindresorhus/globby/blob/master/index.js#L110

Which takes us here:
https://github.com/sindresorhus/globby/blob/master/gitignore.js#L93

^ If I step into that 'fast-glob' call... I become one with the matrix...

----

Anyone have any advice? 

`ember-template-lint` works correctly when i use `ember-cli-template-lint` but I wanted to also lint our in-repo engines and addons...

**Comment by jasonmit** [comment]
globby supports the ability to ignore paths.

https://github.com/ember-template-lint/ember-template-lint/blob/16325086ec8b3e2f9a5c03dc45799aef591fc52d/bin/ember-template-lint.js#L70

Can become:

```js
return filePaths.concat(globby.sync(fileArg, {
  ignore: ['**/dist/**', '**/tmp/**', '**/node_modules/**'],
  gitignore: true
}));
```

This will partially solve the problem for most people.

The issue will persist for people with monorepos because of: https://github.com/sindresorhus/globby/issues/86

To solve that issue, you would need to drop a gitignore in every single one of your packages to ignore `node_modules`, `dist`, `tmp`.

All this to say, does anyone know of a better alternative to globby?  I'll spend the time porting this lib over to it.

**Comment by jasonmit** [comment]
@Duder-onomy curious, do you also have a monorepo?

**Comment by rwjblue** [comment]
Thanks for digging into this @jasonmit. 

Just curious, what does eslint do here?

**Comment by jasonmit** [comment]
> Just curious, what does eslint do here?

Our project kept [the blueprint's `.eslintignore`](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/.eslintignore) in every one of the packages within our monorepo.  

For `.gitignore`, which globby is parsing to figure out what to ignore, is outside of the package `ember-template-lint` is executed within and therefore `ember-template-lint` goes into `tmp`, `dist`, etc.

Are you open to adding [default ignores](https://github.com/ember-template-lint/ember-template-lint/issues/536#issuecomment-453399538) for `dist`, `tmp`, `node_modules`?

**Comment by rwjblue** [comment]
Yes, sounds absolutely fine to me.

**Comment by Duder-onomy** [comment]
I found the root cause of my issues, I have many... (probably too many) linked packages.
The linter was traversing those repos. Unlinking them fixed things and the linter no longer hangs.
